<?php
/**
 * ═══════════════════════════════════════════════════════════════
 *  CRUD Generator - Generate Controller, Model, View otomatis
 * ═══════════════════════════════════════════════════════════════
 * 
 * Cara pakai:
 *   $gen = new CrudGenerator();
 *   $gen->setName('produk')->setFields([...])->generate();
 */
class CrudGenerator
{
    /** @var string */
    private $name;
    /** @var string */
    private $table;
    /** @var string */
    private $label;
    /** @var array */
    private $fields = [];
    /** @var array */
    private $displayColumns = [];

    /**
     * Set nama modul
     */
    public function setName($name)
    {
        $this->name  = strtolower($name);
        $this->table = $this->name;
        $this->label = ucwords(str_replace('_', ' ', $name));
        return $this;
    }

    /**
     * Set nama tabel (bila berbeda dari nama modul)
     */
    public function setTable($table)
    {
        $this->table = $table;
        return $this;
    }

    /**
     * Set label tampilan
     */
    public function setLabel($label)
    {
        $this->label = $label;
        return $this;
    }

    /**
     * Set field definitions
     * 
     * Format per field:
     * [
     *   'name'     => 'nama_kolom',
     *   'label'    => 'Label Kolom',
     *   'type'     => 'text|number|email|textarea|select|date|file',
     *   'required' => true/false,
     *   'options'  => [['value'=>'','label'=>'Pilih']] // untuk type select
     * ]
     */
    public function setFields(array $fields)
    {
        $this->fields = $fields;
        // Auto-set display columns (semua field kecuali password, id, dsb)
        $this->displayColumns = [];
        foreach ($fields as $f) {
            $type = $f['type'] ?? 'text';
            if (!in_array($type, ['password', 'hidden', 'file'])) {
                $this->displayColumns[] = $f['name'];
            }
        }
        return $this;
    }

    /**
     * Jalankan generate semua file
     */
    public function generate(): array
    {
        $results = [];

        // 1. Generate Model
        $results['model'] = $this->generateModel();

        // 2. Generate Controller
        $results['controller'] = $this->generateController();

        // 3. Generate Views (index, create, edit)
        $results['views'] = $this->generateViews();

        // 4. Generate SQL (opsional, untuk referensi)
        $results['sql'] = $this->generateSql();

        return $results;
    }

    /**
     * Generate file Model
     */
    private function generateModel(): string
    {
        $className = ucfirst($this->name);
        $code = <<<PHP
<?php
/**
 * Model: {$this->label}
 * Auto-generated by CRUD Generator
 */
class {$className} extends BaseModel
{
    protected \$table = '{$this->table}';
    protected \$primaryKey = 'id';
}
PHP;

        $path = APP_DIR . "/models/{$className}.php";
        file_put_contents($path, $code);
        return $path;
    }

    /**
     * Generate file Controller
     */
    private function generateController(): string
    {
        $className   = ucfirst($this->name) . 'Controller';
        $modelName   = ucfirst($this->name);
        $modelVar    = lcfirst($modelName);
        $name        = $this->name;
        $label       = $this->label;
        $table       = $this->table;

        // Build field list untuk validasi
        $requiredFields = [];
        $fieldNames     = [];
        foreach ($this->fields as $f) {
            $fieldNames[] = $f['name'];
            if (($f['required'] ?? false) && ($f['type'] ?? 'text') !== 'password') {
                $requiredFields[] = $f['name'];
            }
        }
        $fieldList    = "'" . implode("', '", $fieldNames) . "'";
        $requiredList = "'" . implode("', '", $requiredFields) . "'";

        $code = <<<PHP
<?php
/**
 * Controller: {$label}
 * Auto-generated by CRUD Generator
 */
class {$className} extends BaseController
{
    private {$modelName} \${$modelVar};

    public function __construct()
    {
        // Cek login & akses role
        AuthMiddleware::handle('admin,operator');

        \$this->{$modelVar} = new {$modelName}();
    }

    /**
     * Halaman index / list data
     */
    public function index(): void
    {
        \$page  = (int) (\$_GET['page'] ?? 1);
        \$search = \$this->query('search', '');

        if (\$search) {
            // Cari di semua field tekstual (sederhana)
            \$where = '';
            \$params = [];
            \$conditions = [];
            foreach ([{$fieldList}] as \$field) {
                \$conditions[] = "\`{\$field}\` LIKE ?";
                \$params[] = "%{\$search}%";
            }
            \$where = implode(' OR ', \$conditions);
            \$result = \$this->{$modelVar}->paginate(\$page, 10, \$where, \$params);
        } else {
            \$result = \$this->{$modelVar}->paginate(\$page, 10);
        }

        \$this->view('{$name}/index', [
            'title'      => '{$label}',
            'data'       => \$result['data'],
            'pagination' => \$result,
            'search'     => \$search,
        ]);
    }

    /**
     * Form tambah data
     */
    public function create(): void
    {
        \$this->view('{$name}/create', [
            'title'  => 'Tambah {$label}',
            'fields' => {$modelName}::fields(),
        ]);
    }

    /**
     * Simpan data baru
     */
    public function store(): void
    {
        if (!\$this->isPost()) \$this->redirect('/{$name}/create');

        \$this->validateCsrf();

        \$data = [];
        foreach ([{$fieldList}] as \$field) {
            \$data[\$field] = \$this->input(\$field);
        }

        \$this->{$modelVar}->insert(\$data);

        Session::setFlash('success', 'Data berhasil ditambahkan!');
        \$this->redirect('/{$name}');
    }

    /**
     * Form edit data
     */
    public function edit(\$id): void
    {
        \$data = \$this->{$modelVar}->find(\$id);
        if (!\$data) {
            Session::setFlash('error', 'Data tidak ditemukan.');
            \$this->redirect('/{$name}');
        }

        \$this->view('{$name}/edit', [
            'title'  => 'Edit {$label}',
            'row'    => \$data,
            'fields' => {$modelName}::fields(),
        ]);
    }

    /**
     * Update data
     */
    public function update(\$id): void
    {
        if (!\$this->isPost()) \$this->redirect("/{$name}/edit/{\$id}");

        \$this->validateCsrf();

        \$data = [];
        foreach ([{$fieldList}] as \$field) {
            \$data[\$field] = \$this->input(\$field);
        }

        \$this->{$modelVar}->update(\$id, \$data);

        Session::setFlash('success', 'Data berhasil diupdate!');
        \$this->redirect('/{$name}');
    }

    /**
     * Hapus data
     */
    public function delete(\$id): void
    {
        \$this->{$modelVar}->delete(\$id);
        Session::setFlash('success', 'Data berhasil dihapus!');
        \$this->redirect('/{$name}');
    }
}
PHP;

        $path = APP_DIR . "/controllers/{$className}.php";
        file_put_contents($path, $code);
        return $path;
    }

    /**
     * Generate file View (index, create, edit)
     */
    private function generateViews(): array
    {
        $name  = $this->name;
        $label = $this->label;
        $viewDir = VIEW_DIR . "/{$name}";

        if (!is_dir($viewDir)) {
            mkdir($viewDir, 0755, true);
        }

        $paths = [];

        // ─── Index View ───────────────────────────────
        // Build table header
        $thRows = '';
        foreach ($this->displayColumns as $col) {
            $colLabel = ucwords(str_replace('_', ' ', $col));
            $thRows .= "                            <th>{$colLabel}</th>\n";
        }

        // Build table body
        $tdRows = '';
        foreach ($this->displayColumns as $col) {
            $tdRows .= "                            <td><?= htmlspecialchars(\$row['{$col}']) ?></td>\n";
        }

        $indexCode = <<<PHP
<?php
/**
 * View: {$label} - Index
 */
\$pageTitle = \$title ?? '{$label}';
?>

<!-- Flash message -->
<?php if (\$msg = Session::getFlash('success')): ?>
    <script>window._toastr_success = '<?= addslashes(\$msg) ?>';</script>
<?php endif; ?>
<?php if (\$msg = Session::getFlash('error')): ?>
    <script>window._toastr_error = '<?= addslashes(\$msg) ?>';</script>
<?php endif; ?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"><?= \$pageTitle ?></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="<?= URL::base('/dashboard') ?>">Dashboard</a></li>
                    <li class="breadcrumb-item active"><?= \$pageTitle ?></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Daftar {$label}</h3>
                <div class="card-tools">
                    <a href="<?= URL::base('/{$name}/create') ?>" class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Tambah Data
                    </a>
                </div>
            </div>
            <div class="card-body">
                <!-- Search -->
                <form method="GET" action="<?= URL::base('/{$name}') ?>" class="mb-3">
                    <div class="input-group input-group-sm" style="max-width:300px;">
                        <input type="text" name="search" class="form-control" placeholder="Cari..."
                               value="<?= htmlspecialchars(\$search ?? '') ?>">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th width="50">No</th>
{$thRows}
                                <th width="150">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty(\$data)): ?>
                            <tr>
                                <td colspan="99" class="text-center text-muted py-3">
                                    <i class="fas fa-inbox fa-2x d-block mb-2"></i>
                                    Belum ada data. Klik "Tambah Data" untuk memulai.
                                </td>
                            </tr>
                            <?php else: ?>
                            <?php \$no = (\$pagination['page'] - 1) * \$pagination['per_page'] + 1; ?>
                            <?php foreach (\$data as \$row): ?>
                            <tr>
                                <td><?= \$no++ ?></td>
{$tdRows}
                                <td>
                                    <a href="<?= URL::base('/{$name}/edit/' . \$row['id']) ?>"
                                       class="btn btn-warning btn-xs" title="Edit">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="<?= URL::base('/{$name}/delete/' . \$row['id']) ?>"
                                       class="btn btn-danger btn-xs"
                                       onclick="return confirm('Yakin ingin menghapus data ini?')"
                                       title="Hapus">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>

                <!-- Pagination -->
                <?php if ((\$pagination['total_pages'] ?? 1) > 1): ?>
                <nav>
                    <ul class="pagination pagination-sm justify-content-center">
                        <?php for (\$i = 1; \$i <= \$pagination['total_pages']; \$i++): ?>
                        <li class="page-item <?= \$i == \$pagination['page'] ? 'active' : '' ?>">
                            <a class="page-link" href="?page=<?= \$i ?>&search=<?= urlencode(\$search ?? '') ?>">
                                <?= \$i ?>
                            </a>
                        </li>
                        <?php endfor; ?>
                    </ul>
                </nav>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
PHP;
        $paths[] = $viewDir . '/index.php';
        file_put_contents($viewDir . '/index.php', $indexCode);

        // ─── Create View ─────────────────────────────
        $formFields = $this->buildFormFields();
        
        $createCode = <<<PHP
<?php
/**
 * View: {$label} - Create
 */
\$pageTitle = \$title ?? 'Tambah {$label}';
?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"><?= \$pageTitle ?></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="<?= URL::base('/dashboard') ?>">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="<?= URL::base('/{$name}') ?>">{$label}</a></li>
                    <li class="breadcrumb-item active">Tambah</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Form Tambah {$label}</h3>
            </div>
            <form method="POST" action="<?= URL::base('/{$name}/store') ?>">
                <div class="card-body">
                    <?= Security::csrfField() ?>
{$formFields}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save"></i> Simpan
                    </button>
                    <a href="<?= URL::base('/{$name}') ?>" class="btn btn-default">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
PHP;
        $paths[] = $viewDir . '/create.php';
        file_put_contents($viewDir . '/create.php', $createCode);

        // ─── Edit View ──────────────────────────────
        $editFormFields = $this->buildFormFields(true);
        
        $editCode = <<<PHP
<?php
/**
 * View: {$label} - Edit
 */
\$pageTitle = \$title ?? 'Edit {$label}';
?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"><?= \$pageTitle ?></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="<?= URL::base('/dashboard') ?>">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="<?= URL::base('/{$name}') ?>">{$label}</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Form Edit {$label}</h3>
            </div>
            <form method="POST" action="<?= URL::base('/{$name}/edit/' . \$row['id']) ?>">
                <div class="card-body">
                    <?= Security::csrfField() ?>
{$editFormFields}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save"></i> Update
                    </button>
                    <a href="<?= URL::base('/{$name}') ?>" class="btn btn-default">Batal</a>
                </div>
            </form>
        </div>
    </div>
</div>
PHP;
        $paths[] = $viewDir . '/edit.php';
        file_put_contents($viewDir . '/edit.php', $editCode);

        return $paths;
    }

    /**
     * Build HTML form fields dari definisi
     */
    private function buildFormFields(bool $isEdit = false): string
    {
        $html = '';
        $rowVar = $isEdit ? "\$row['%s']" : "''";

        foreach ($this->fields as $field) {
            $name     = $field['name'];
            $label    = $field['label'] ?? ucwords(str_replace('_', ' ', $name));
            $type     = $field['type'] ?? 'text';
            $required = ($field['required'] ?? false) ? 'required' : '';
            $value    = sprintf($rowVar, $name);

            $html .= <<<HTML

                        <div class="form-group">
                            <label for="{$name}">{$label}</label>

HTML;

            switch ($type) {
                case 'textarea':
                    $html .= <<<HTML
                            <textarea name="{$name}" id="{$name}" class="form-control" rows="3"
                                      {$required}><?= htmlspecialchars({$value}) ?></textarea>

HTML;
                    break;

                case 'select':
                    $html .= <<<HTML
                            <select name="{$name}" id="{$name}" class="form-control" {$required}>

HTML;
                    if (!empty($field['options'])) {
                        foreach ($field['options'] as $opt) {
                            $optValue = $opt['value'] ?? '';
                            $optLabel = $opt['label'] ?? $optValue;
                            $html .= <<<HTML
                                <option value="{$optValue}" <?= ({$value}) == '{$optValue}' ? 'selected' : '' ?>>
                                    {$optLabel}
                                </option>

HTML;
                        }
                    }
                    $html .= "                            </select>\n";
                    break;

                default: // text, number, email, date, etc.
                    $html .= <<<HTML
                            <input type="{$type}" name="{$name}" id="{$name}" class="form-control"
                                   value="<?= htmlspecialchars({$value}) ?>" {$required}>

HTML;
            }

            $html .= "                        </div>\n";
        }

        return $html;
    }

    /**
     * Generate SQL CREATE TABLE untuk referensi
     */
    private function generateSql(): string
    {
        $cols = [];
        $cols[] = "    `id` INT AUTO_INCREMENT PRIMARY KEY";

        foreach ($this->fields as $field) {
            $name = $field['name'];
            $type = $field['type'] ?? 'text';
            $null = ($field['required'] ?? false) ? 'NOT NULL' : 'NULL';

            switch ($type) {
                case 'number':   $sqlType = 'INT'; break;
                case 'email':    $sqlType = 'VARCHAR(100)'; break;
                case 'textarea': $sqlType = 'TEXT'; break;
                case 'date':     $sqlType = 'DATE'; break;
                case 'select':   $sqlType = 'VARCHAR(50)'; break;
                default:         $sqlType = 'VARCHAR(255)'; break;
            }

            $cols[] = "    `{$name}` {$sqlType} {$null}";
        }

        $cols[] = "    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
        $cols[] = "    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";

        $columns = implode(",\n", $cols);

        return "-- SQL untuk tabel {$this->table}\nCREATE TABLE `{$this->table}` (\n{$columns}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
    }
}
